spring.application.name=BMS
# 1. Connection Details
spring.datasource.url=jdbc:postgresql://localhost:5432/BMS_dev
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# 2. Driver Class
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Hibernate / JPA Strategy
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
